# Generated by Django 4.0.4 on 2022-05-16 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_banner_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='active',
            field=models.CharField(choices=[('active', 'active'), ('no_active', 'no_active')], default='no_active', max_length=16),
        ),
    ]
