# Generated by Django 4.0.4 on 2022-05-17 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_alter_banner_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slider',
            field=models.CharField(choices=[('buildings', 'buildings'), ('design', 'design')], default='buildings', max_length=255),
        ),
        migrations.AlterField(
            model_name='banner',
            name='active',
            field=models.CharField(choices=[('active', 'active'), ('no active', 'no active')], default='no_active', max_length=16),
        ),
    ]
