# Generated by Django 4.0.4 on 2022-05-17 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0006_category_slider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default=2, upload_to='product/', verbose_name='Haryt surat'),
            preserve_default=False,
        ),
    ]
