# Generated by Django 4.0.4 on 2022-05-18 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0009_alter_category_slider_alter_product_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('mini_desc', models.TextField()),
                ('desc', models.TextField()),
                ('image_one', models.ImageField(blank=True, null=True, upload_to='aboutUs/', verbose_name='kompaniya barada maglumat')),
                ('image_second', models.ImageField(blank=True, null=True, upload_to='aboutUs/', verbose_name='kompaniya barada maglumat')),
                ('image_three', models.ImageField(blank=True, null=True, upload_to='aboutUs/', verbose_name='kompaniya barada maglumat')),
                ('image_last', models.ImageField(blank=True, null=True, upload_to='aboutUs/', verbose_name='kompaniya barada maglumat')),
            ],
        ),
    ]
