# Generated by Django 4.0.4 on 2022-05-18 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0014_category_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='desc',
        ),
        migrations.AddField(
            model_name='about',
            name='prod_about',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
