# Generated by Django 4.0.4 on 2022-05-18 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0015_remove_category_desc_about_prod_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('desc', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='footer about/', verbose_name='footer surat')),
            ],
        ),
    ]
