# Generated by Django 4.0.4 on 2022-05-18 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0016_footerabout'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('phone', models.IntegerField(max_length=15)),
                ('mobile_phone', models.IntegerField(max_length=15)),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
    ]
