# Generated by Django 4.0.4 on 2022-05-18 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0018_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='mobile_phone',
            field=models.IntegerField(),
        ),
    ]
