# Generated by Django 4.0.4 on 2022-05-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0022_certification'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='logo',
            field=models.ImageField(default=1, upload_to='logo/', verbose_name='logo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='slider',
            field=models.CharField(blank=True, choices=[('buildings', '1'), ('design', '2'), ('isolation', '3')], default='buildings', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='certification',
            name='image',
            field=models.ImageField(upload_to='sertifikat about/', verbose_name='sertifikat surat'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slider',
            field=models.CharField(choices=[('buildings', '1'), ('design', '2'), ('isolation', '3')], default='buildings', max_length=255),
        ),
    ]
