# Generated by Django 4.0.4 on 2022-05-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0023_about_logo_alter_category_slider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=4, max_digits=12),
            preserve_default=False,
        ),
    ]
