# Generated by Django 4.0.4 on 2022-05-19 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0024_product_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'О нас', 'verbose_name_plural': 'О нас'},
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Адресс', 'verbose_name_plural': 'Адрессы'},
        ),
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': 'Баннер', 'verbose_name_plural': 'Баннеры'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='certification',
            options={'verbose_name': 'Сертификат', 'verbose_name_plural': 'Сертификаты'},
        ),
        migrations.AlterModelOptions(
            name='footerabout',
            options={'verbose_name': 'Нижнее описание', 'verbose_name_plural': 'Нижнее описание'},
        ),
        migrations.AlterModelOptions(
            name='map',
            options={'verbose_name': 'Карта', 'verbose_name_plural': 'Карты'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новосить', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterField(
            model_name='about',
            name='desc',
            field=models.TextField(verbose_name='Giňişleýin beýany'),
        ),
        migrations.AlterField(
            model_name='about',
            name='image_last',
            field=models.ImageField(blank=True, null=True, upload_to='aboutUs/', verbose_name='kompaniya barada surat'),
        ),
        migrations.AlterField(
            model_name='about',
            name='image_one',
            field=models.ImageField(blank=True, null=True, upload_to='aboutUs/', verbose_name='kompaniya barada surat'),
        ),
        migrations.AlterField(
            model_name='about',
            name='image_second',
            field=models.ImageField(blank=True, null=True, upload_to='aboutUs/', verbose_name='kompaniya barada surat'),
        ),
        migrations.AlterField(
            model_name='about',
            name='image_three',
            field=models.ImageField(blank=True, null=True, upload_to='aboutUs/', verbose_name='kompaniya barada surat'),
        ),
        migrations.AlterField(
            model_name='about',
            name='mini_desc',
            field=models.TextField(verbose_name='Gysgaça beýany'),
        ),
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Ady'),
        ),
        migrations.AlterField(
            model_name='address',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email poçtasy'),
        ),
        migrations.AlterField(
            model_name='address',
            name='location',
            field=models.CharField(max_length=255, verbose_name='Ýerleşýän ýeri'),
        ),
        migrations.AlterField(
            model_name='address',
            name='mobile_phone',
            field=models.IntegerField(verbose_name='El telefon'),
        ),
        migrations.AlterField(
            model_name='address',
            name='phone',
            field=models.IntegerField(verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='address',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Ady'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='active',
            field=models.CharField(blank=True, choices=[('active', 'active')], default='no_active', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ady'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ady'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slider',
            field=models.CharField(blank=True, choices=[('buildings', '1'), ('design', '2'), ('isolation', '3')], default='buildings', max_length=255, null=True, verbose_name='Haryt çalşyrjy slider'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='image',
            field=models.ImageField(upload_to='sertifikat about/', verbose_name='sertifikatyň surat'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Ady'),
        ),
        migrations.AlterField(
            model_name='footerabout',
            name='desc',
            field=models.TextField(verbose_name='Gysgaça beýany'),
        ),
        migrations.AlterField(
            model_name='footerabout',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='footer about/', verbose_name='Aşakdaky bölekdäki surat'),
        ),
        migrations.AlterField(
            model_name='footerabout',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ady'),
        ),
        migrations.AlterField(
            model_name='map',
            name='map',
            field=models.TextField(verbose_name='Karta'),
        ),
        migrations.AlterField(
            model_name='news',
            name='desc',
            field=models.TextField(verbose_name='Giňişleýin beýany'),
        ),
        migrations.AlterField(
            model_name='news',
            name='mini_desc',
            field=models.TextField(verbose_name='Gysgaça beýany'),
        ),
        migrations.AlterField(
            model_name='news',
            name='right_desc',
            field=models.TextField(verbose_name=' Sag tarapdaky gysgaça beýany'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ady'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.category', verbose_name='Kategoriýasy'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Giňişleýin beýany'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product/', verbose_name='Harydyň surat'),
        ),
        migrations.AlterField(
            model_name='product',
            name='mini_desc',
            field=models.TextField(blank=True, null=True, verbose_name='Gysgaça beýany'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ady'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Bahasy'),
        ),
    ]
