# Generated by Django 4.0.4 on 2022-05-19 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='logo/', verbose_name='logo')),
                ('title', models.CharField(max_length=255, verbose_name='Ady')),
                ('mini_desc', models.TextField(verbose_name='Gysgaça beýany')),
                ('desc', models.TextField(verbose_name='Giňişleýin beýany')),
                ('prod_about', models.TextField()),
                ('image_one', models.ImageField(blank=True, null=True, upload_to='aboutUs/', verbose_name='kompaniya barada surat')),
                ('image_second', models.ImageField(blank=True, null=True, upload_to='aboutUs/', verbose_name='kompaniya barada surat')),
                ('image_three', models.ImageField(blank=True, null=True, upload_to='aboutUs/', verbose_name='kompaniya barada surat')),
                ('image_last', models.ImageField(blank=True, null=True, upload_to='aboutUs/', verbose_name='kompaniya barada surat')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Ady')),
                ('location', models.CharField(max_length=255, verbose_name='Ýerleşýän ýeri')),
                ('phone', models.IntegerField(verbose_name='Telefon')),
                ('mobile_phone', models.IntegerField(verbose_name='El telefon')),
                ('email', models.EmailField(max_length=254, verbose_name='Email poçtasy')),
            ],
            options={
                'verbose_name': 'Адресс',
                'verbose_name_plural': 'Адрессы',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ady')),
                ('image', models.ImageField(blank=True, null=True, upload_to='banner/', verbose_name='Banner surat')),
                ('active', models.CharField(blank=True, choices=[('active', 'active'), ('no active', 'no active')], default='no_active', max_length=16, null=True)),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ady')),
                ('slider', models.CharField(blank=True, choices=[('buildings', '1'), ('design', '2'), ('isolation', '3')], default='buildings', max_length=255, null=True, verbose_name='Haryt çalşyrjy slider')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Ady')),
                ('image', models.ImageField(upload_to='sertifikat about/', verbose_name='sertifikatyň surat')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
            },
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='FooterAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ady')),
                ('desc', models.TextField(verbose_name='Gysgaça beýany')),
                ('image', models.ImageField(blank=True, null=True, upload_to='footer about/', verbose_name='Aşakdaky bölekdäki surat')),
            ],
            options={
                'verbose_name': 'Нижнее описание',
                'verbose_name_plural': 'Нижнее описание',
            },
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map', models.TextField(verbose_name='Karta')),
            ],
            options={
                'verbose_name': 'Карта',
                'verbose_name_plural': 'Карты',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ady')),
                ('mini_desc', models.TextField(verbose_name='Gysgaça beýany')),
                ('desc', models.TextField(verbose_name='Giňişleýin beýany')),
                ('right_desc', models.TextField(verbose_name=' Sag tarapdaky gysgaça beýany')),
            ],
            options={
                'verbose_name': 'Новосить',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ady')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product/', verbose_name='Harydyň surat')),
                ('mini_desc', models.TextField(blank=True, null=True, verbose_name='Gysgaça beýany')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Giňişleýin beýany')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Bahasy')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slider', models.CharField(choices=[('buildings', '1'), ('design', '2'), ('isolation', '3')], default='buildings', max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TmApp.category', verbose_name='Kategoriýasy')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
