# Generated by Django 4.0.4 on 2022-05-19 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TmApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='active',
            field=models.CharField(blank=True, choices=[('active', 'active')], default='no_active', max_length=16, null=True),
        ),
    ]
