# Generated by Django 4.0.4 on 2022-05-20 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TmApp', '0002_alter_banner_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Salgy', 'verbose_name_plural': 'Salgylar'},
        ),
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': 'Banner', 'verbose_name_plural': 'Bannerlar'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Kategoriýa', 'verbose_name_plural': 'Kategoriýalar'},
        ),
        migrations.AlterModelOptions(
            name='certification',
            options={'verbose_name': 'Sertifikat', 'verbose_name_plural': 'Sertifikatlar'},
        ),
        migrations.AlterModelOptions(
            name='footerabout',
            options={'verbose_name': 'Aşakdaky beýan', 'verbose_name_plural': 'Aşakdaky beýanlar'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Habar', 'verbose_name_plural': 'Habarlar'},
        ),
        migrations.AddField(
            model_name='product',
            name='line_one',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='line_second',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='line_three',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
